import { groupBy } from "lodash";
import type { Restaurant } from "./types";

// prettier-ignore
export const restaurants: Restaurant[] = [
  {
    id: "piccola-roma-beilen",
    name: "Piccola Roma",
    location: "Beilen",
    phone: "0593 52 72 88",
    menu: [
      {"category": "Pizze", "id":  1, "name": "Bambini", "description": "kinderpizza met tomatensaus, kaas, ham of salami", "price": "€ 5,50"},
      {"category": "Pizze", "id":  2, "name": "margherita", "description": "tomatensaus, kaas", "price": "€ 9,50"},
      {"category": "Pizze", "id":  3, "name": "Napoletana", "description": "tomatensaus, kaas, ansjovis & kappertjes", "price": "€ 11,00"},
      {"category": "Pizze", "id":  4, "name": "Funghi", "description": "tomatensaus, kaas & champignons", "price": "€ 11,00"},
      {"category": "Pizze", "id":  5, "name": "Prosciutto", "description": "tomatensaus, kaas & ham", "price": "€ 11,00"},
      {"category": "Pizze", "id":  6, "name": "Salame", "description": "tomatensaus, kaas & salami", "price": "€ 11,00"},
      {"category": "Pizze", "id":  7, "name": "Tonno", "description": "tomatensaus, kaas & tonijn", "price": "€ 12,50"},
      {"category": "Pizze", "id":  8, "name": "Campagnola", "description": "tomatensaus, kaas, champignons, ham, paprika & uien", "price": "€ 13,00"},
      {"category": "Pizze", "id":  9, "name": "Quattro stagioni", "description": "tomatensaus, kaas, champignons, ham, salami, ansjovis, olijven & kappertjes", "price": "€ 13,75"},
      {"category": "Pizze", "id": 10, "name": "Mista", "description": "tomatensaus, kaas, champignons, ham, salami, gerookte zalm & garnalen", "price": "€ 13,75"},
      {"category": "Pizze", "id": 11, "name": "Salsiccia sardo", "description": "tomatensaus, buffelmozzarella, Sardijnse salami, kappertjes, verse tomaat & knoflook pikant!", "price": "€ 15,50"},
      {"category": "Pizze", "id": 12, "name": "Peperone", "description": "tomatensaus, kaas, champignons, paprika, uien & spaanse pepers", "price": "€ 13,75"},
      {"category": "Pizze", "id": 13, "name": "Calzone", "description": "dubbelgeslagen pizza met tomatensaus, kaas, ham & salami", "price": "€ 14,50"},
      {"category": "Pizze", "id": 14, "name": "Costa smeralda", "description": "tomatensaus, kaas, zalm, 4 gamba’s, ananas, ui & spaanse pepers", "price": "€ 17,50"},
      {"category": "Pizze", "id": 15, "name": "Carbonara", "description": "tomatensaus, kaas, ham, salami, spek & rosbief", "price": "€ 14,50"},
      {"category": "Pizze", "id": 16, "name": "Frutti di mare", "description": "tomatensaus, kaas, gerookte zalm, garnalen, mosselen & ansjovis", "price": "€ 16,00"},
      {"category": "Pizze", "id": 17, "name": "Pizza de buongustaio", "description": "voor fijnproevers met tomatensaus, kaas, champignons, salami, fricandeau, asperges, paprika, gorgonzola & ossenhaas", "price": "€ 17,00"},
      {"category": "Pizze", "id": 18, "name": "Sardagnola", "description": "tomatensaus, buffelmozzarella, tonijn, garnalen, paprika, ui & knoflook", "price": "€ 15,00"},
      {"category": "Pizze", "id": 19, "name": "Funghi alla marinara", "description": "tomatensaus, kaas, champignons, gerookte zalm, garnalen & mosselen", "price": "€ 15,00"},
      {"category": "Pizze", "id": 20, "name": "Fantasia carne", "description": "fantasie van de kok (vlees)", "price": "€ 13,75"},
      {"category": "Pizze", "id": 21, "name": "Svedese", "description": "tomatensaus, kaas, ham, ui & ei", "price": "€ 13,00"},
      {"category": "Pizze", "id": 22, "name": "Vegetariana", "description": "tomatensaus, kaas, champignons, asperges, artisjokken, paprika, olijven & ui", "price": "€ 13,75"},
      {"category": "Pizze", "id": 23, "name": "Del re", "description": "pizza van de koning met tomatensaus, kaas, champignons, ham, salami, spek, fricandeau, paprika, ananas, ossenhaas & spaanse pepers", "price": "€ 17,00"},
      {"category": "Pizze", "id": 24, "name": "Pizza alla gorgonzola", "description": "tomatensaus, kaas, ham, salami, asperges, gorgonzola, basilicum & verse groene peperkorrels", "price": "€ 15,25"},
      {"category": "Pizze", "id": 25, "name": "Romina", "description": "tomatensaus, kaas, champignons, ham, fricandeau, gerookte zalm, asperges, paprika, olijven & ui", "price": "€ 15,25"},
      {"category": "Pizze", "id": 26, "name": "Chiara", "description": "tomatensaus, kaas, ham, paprika, ui, ananas & verse tomaat", "price": "€ 13,75"},
      {"category": "Pizze", "id": 27, "name": "Gamberi", "description": "tomatensaus, kaas, garnalen, paprika, basilicum & knoflook", "price": "€ 15,50"},
      {"category": "Pizze", "id": 28, "name": "Vongole", "description": "tomatensaus, kaas, garnalen, vongole (schelpdieren), paling, krab, ansjovis & ui", "price": "€ 16,00"},
      {"category": "Pizze", "id": 29, "name": "Della sirena", "description": "pizza van de zeemeermin met tomatensaus, kaas, gerookte zalm, mosselen, vongole, 3 gamba’s & ui", "price": "€ 16,50"},
      {"category": "Pizze", "id": 30, "name": "Quattro formaggi", "description": "tomatensaus, kaas, ham, mozzarella, gorgonzola, gruyere, verse groene peperkorrels & basilicum", "price": "€ 15,50"},
      {"category": "Pizze", "id": 31, "name": "Sardo", "description": "tomatensaus, kaas, ham, artisjokken, mozzarella, gorgonzola, pecorino & olijven", "price": "€ 16,00"},
      {"category": "Pizze", "id": 32, "name": "Piccola Roma", "description": "tomatensaus, kaas, champignons, ham, artisjokken, asperges, ansjovis, olijven & ui", "price": "€ 14,25"},
      {"category": "Pizze", "id": 33, "name": "Olandese", "description": "tomatensaus, kaas, ham, spek, fricandeau, asperges, ui & ei", "price": "€ 14,25"},
      {"category": "Pizze", "id": 34, "name": "Salmone e funghi", "description": "tomatensaus, kaas, champignons, gerookte zalm & citroen", "price": "€ 13,00"},
      {"category": "Pizze", "id": 35, "name": "Mediterrana", "description": "tomatensaus, kaas, salami, ananas, parika, gorgonzola", "price": "€ 13,00"},
      {"category": "Pizze", "id": 36, "name": "Piëtra", "description": "tomatensaus, kaas, tonijn, spek, ui & knoflook pikant", "price": "€ 14,25"},
      {"category": "Pizze", "id": 37, "name": "Pizzaiola", "description": "tomatensaus, kaas, ossenhaas, mozzarella, kappertjes, olijven, oregano, basilicum & groene peperkorrels", "price": "€ 16,50"},
      {"category": "Pizze", "id": 38, "name": "Mamma mia", "description": "tomatensaus, kaas, champignons, fricandeau, gorgonzola, mozzarella, ananas & spaanse pepers", "price": "€ 17,00"},
      {"category": "Pizze", "id": 39, "name": "Arcobaleno", "description": "tomatensaus, kaas, gorgonzola, mozzarella, paprika & ananas", "price": "€ 16,50"},
      {"category": "Pizze", "id": 40, "name": "Fantasia pesce", "description": "fantasie van de kok (vis)", "price": "€ 17,00"},
      {"category": "Pizze", "id": 41, "name": "Raffaella", "description": "tomatensaus, kaas, ham, salami, asperges, paprika, ui & ei", "price": "€ 14,25"},
      {"category": "Pizze", "id": 42, "name": "Quattro stagioni", "description": "tomatensaus, kaas, champignons, ham, salami, artisjokken, paprika, speciale olijven & kappertjes", "price": "€ 14,25"},
      {"category": "Pizze", "id": 43, "name": "Roberto", "description": "tomatensaus, kaas, champignons, tonijn, asperges, paling, peterselie & knoflook pikant", "price": "€ 16,50"},
      {"category": "Pizze", "id": 44, "name": "Vegetariana con", "description": "tomatensaus, kaas, champignons, artisjok, asperges, peer, frutta e gorgonzola ananas, paprika, gorgonzola, olijven, ui & spaanse pepers", "price": "€ 16,50"},
      {"category": "Pizze", "id": 45, "name": "Antonio", "description": "tomatensaus, kaas, ham, salami, spek, gorgonzola & spaanse pepers", "price": "€ 15,50"},
      {"category": "Pizze", "id": 46, "name": "Romagnola", "description": "tomatensaus, buffelmozzarella, gerookte zalm, rucola, parmezaanse kaas & balsamico azijn", "price": "€ 15,50"},
      {"category": "Pizze", "id": 47, "name": "Gianna", "description": "tomatensaus, kaas, champignons, ham, tonijn, asperges, paprika, verse tomaten & knoflook", "price": "€ 15,50"},
      {"category": "Pizze", "id": 48, "name": "Tropicale", "description": "tomatensaus, kaas, gorgonzola, mozzarella, mango, kiwi, parmaham & 3 gamba’s", "price": "€ 16,50"},
      {"category": "Pizze", "id": 49, "name": "Calzone speciale", "description": "dubbelgeslagen pizza met tomatensaus, kaas, ham, salami, fricandeau, spek & paprika", "price": "€ 15,50"},
      {"category": "Pizze", "id": 50, "name": "Vesuvio", "description": "tomatensaus, kaas, champignons & salami", "price": "€ 11,50"},
      {"category": "Pizze", "id": 51, "name": "Vulcano", "description": "tomatensaus, kaas, champignons & ham", "price": "€ 11,50"},
      {"category": "Pizze", "id": 52, "name": "Della nonna", "description": "tomatensaus, kaas, mozzarella, venkelsalami, knoflook & pikant", "price": "€ 13,25"},
      {"category": "Pizze", "id": 53, "name": "Dell ‘nonno", "description": "tomatensaus, kaas, mozzarella, ansjovis, paprika, kappertjes, tonijn & knoflook", "price": "€ 13,75"},
      {"category": "Pizze", "id": 54, "name": "Hawaii", "description": "tomatensaus, kaas, ham & ananas", "price": "€ 11,50"},
      {"category": "Pizze", "id": 55, "name": "Montanara", "description": "tomatensaus, kaas, champignons, ham & salami", "price": "€ 12,75"},
      {"category": "Pizze", "id": 56, "name": "Con frutta", "description": "vruchtenpizza met o.a. tomatensaus, kaas, banaan, ananas, kiwi & peer", "price": "€ 13,75"},
      {"category": "Pizze", "id": 57, "name": "Al capone", "description": "tomatensaus, kaas, champignons, salami, asperges, paprika, parmezaanse kaas, ossenhaas, gorgonzola & spaanse pepers", "price": "€ 17,00"},
      {"category": "Pizze", "id": 58, "name": "Santa Lucia speciale", "description": "tomatensaus, kaas, champignons, ham, salami, artisjokken, asperges, ui & spaanse pepers", "price": "€ 14,75"},
      {"category": "Pizze", "id": 59, "name": "Paesana", "description": "van het platteland met tomatensaus, kaas, champignons, ham, salami, spek & ui", "price": "€ 14,75"},
      {"category": "Pizze", "id": 60, "name": "Bandito", "description": "tomatensaus, kaas, champignons, salami, asperges, parmezaanse kaas, gorgonzola, ossenhaas, bolognesesaus & spaanse pepers", "price": "€ 17,00"},
      {"category": "Pizze", "id": 61, "name": "Capriciosa speciale", "description": "tomatensaus, kaas, champignons, ham, salami, zalm, garnalen, paprika, ui, olijven & ansjovis", "price": "€ 16,00"},
      {"category": "Pizze", "id": 62, "name": "Carbonara speciale", "description": "tomatensaus, kaas, ham, salami, spek, rosbief, ui & ei", "price": "€ 15,25"},
      {"category": "Pizze", "id": 63, "name": "Fantasia vegetariano", "description": "fantasie van de kok (vegetarisch)", "price": "€ 15,50"},
      {"category": "Pizze", "id": 64, "name": "Bolognese", "description": "bolognesesaus met gehakt & kaas", "price": "€ 11,00"},
      {"category": "Pizze", "id": 65, "name": "Rosaria", "description": "tomatensaus, kaas, parmaham, rucola, parmezaanse kaas, olijf olie & balsamico azijn", "price": "€ 15,50"},

      { "category": "Antipasti (voorgerechten)", "id": "A", "name": "Panini burro", "description": "pizzabroodjes met kruidenboter", "price": "5.50" },
      {"category": "Antipasti (voorgerechten)", "id":"B", "name": "Prosciutto e melone", "description": "parmaham met meloen", "price": "€ 11,00"},
      {"category": "Antipasti (voorgerechten)", "id":"C", "name": "Antipasto della casa", "description": "gemengd voorgerecht met o.a. parmaham, salami", "price": "€ 13,00"},
      {"category": "Antipasti (voorgerechten)", "id":"D", "name": "Salade", "price": "€ 4,50"},
      {"category": "Antipasti (voorgerechten)", "id":"E", "name": "Tonijnsalade", "price": "€ 6,50 "},

      {"category": "Spaghetti/maccheroni", "id": "A", "name": "Bolognese", "description": "tomatensaus met o.a. gehakt, Parmezaanse kaas", "price": "€ 1,50"},
      {"category": "Spaghetti/maccheroni", "id": "B", "name": "Alla Carbonara", "description": "roomsaus met ham, spek, uien, ei, knoflook, peterselie, Parmezaanse kaas", "price": "€ 11,50"},
      {"category": "Spaghetti/maccheroni", "id": "C", "name": "Alla Gorgonzola", "description": "roomsaus met gorgonzola, mozzarella, tomaat, Parmezaanse kaas, knoflook en peterselie", "price": "€ 12,50"},
      {"category": "Spaghetti/maccheroni", "id": "D", "name": "Con Tonno", "description": "tonijn, peterselie, knoflook, witte wijn", "price": "€ 12,00"},
      {"category": "Spaghetti/maccheroni", "id": "E", "name": "Alla Zingara", "description": "champignons, uien, paprika, peterselie, tomaat, knoflook, spaanse pepers en parmezaanse kaas", "price": "€ 12,50"},
      {"category": "Spaghetti/maccheroni", "id": "F", "name": "Alla arrabiata", "description": "tomatensaus, pikant!, peterselie, knoflook", "price": "€ 10,50"},

      {"category": "Verse deeggerechten", "id": "A", "name": "Tortellini", "description": "maccheroni gevuld met vlees met bolognese saus en Parmezaanse kaas", "price": "€ 13,00"},
      {"category": "Verse deeggerechten", "id": "B", "name": "Ravioli", "description": "maccheroni gevuld met vlees met bolognese saus en Parmezaanse kaas", "price": "€ 12,50"},
      {"category": "Verse deeggerechten", "id": "C", "name": "Ravioli 4 formaggi", "description": "maccheroni kussentjes gevuld met vlees in 4 soorten kaas met roomsaus", "price": "€ 13,50"},
      {"category": "Verse deeggerechten", "id": "D", "name": "Lasagna", "description": "bolognese saus met bechamel, kaas, salami", "price": "€ 12,50"},
      {"category": "Verse deeggerechten", "id": "E", "name": "Lasagna gorgonzola", "description": "bolognesesaus met bechamel, kaas, salami, gorgonzola kaas", "price": "€ 13,50"},

      {"category": "Vleesgerechten", "id": "A", "name": "Scaloppa al vino bianco", "description": "plakjes varkenshaas gebakken in witte wijn met roomsaus", "price": "€ 19,00"},
      {"category": "Vleesgerechten", "id": "B", "name": "Scaloppa alla marsala", "description": "plakjes varkenshaas gebakken in witte wijn en marsala – zoet!", "price": "€ 19,00"},
      {"category": "Vleesgerechten", "id": "C", "name": "Scaloppa alla gorgonzola", "description": "plakjes varkenshaas gebakken in witte wijn met gorgonzola roomsaus", "price": "€ 20,00"},
      {"category": "Vleesgerechten", "id": "D", "name": "Scaloppa alla bolognese", "description": "plakjes varkenshaas gebakken in witte wijn met bolognesesaus", "price": "€ 19,00"},
      {"category": "Vleesgerechten", "id": "E", "name": "Scaloppa alla zingara", "description": "plakjes varkenshaas gebakken in witte wijn met champignons, uien, paprika in tomatensaus – beetje pikant!", "price": "€ 19,00"},
      {"category": "Vleesgerechten", "id": "F", "name": "Scaloppa ai funghi", "description": "plakjes varkenshaas in witte wijn roomsaus met champignons", "price": "€ 19,00"},
      {"category": "Vleesgerechten", "id": "G", "name": "Filetto alla griglia", "description": "geroosterde ossenhaas met knoflook, peterselie", "price": "€ 27,50"},
      {"category": "Vleesgerechten", "id": "H", "name": "Filetto ai funghi", "description": "geroosterde ossenhaas met champignons, room, witte wijn, cognac", "price": "€ 28,00"},
      {"category": "Vleesgerechten", "id": "I", "name": "Filetto alla’arrabiata", "description": "ossenhaas, knoflook, peterselie, tomatensaus, pepers, beetje room", "price": "€ 28,00"},
      {"category": "Vleesgerechten", "id": "J", "name": "Entrecôte alla griglia", "description": "geroosterde entrecôte met knoflook, peterselie", "price": "€ 21,00"},
      {"category": "Vleesgerechten", "id": "K", "name": "Entrecôte ai funghi", "description": "geroosterde entrecôte met champignons, knoflook, peterselie in roomsaus", "price": "€ 22,00"},
      {"category": "Vleesgerechten", "id": "L", "name": "Pollo al vino bianco", "description": "kipfilet in witte wijn met roomsaus", "price": "€ 18,00"},
      {"category": "Vleesgerechten", "id": "M", "name": "Pollo alla gorgonzola", "description": "kipfilet in witte wijn met gorgonzola saus", "price": "€ 18,50"},
      {"category": "Vleesgerechten", "id": "N", "name": "Pollo alla bolognese", "description": "kipfilet in witte wijn met bolognesesaus", "price": "€ 18,50"},
      {"category": "Vleesgerechten", "id": "O", "name": "Pollo all’ arrabiata", "description": "kipfilet in witte wijn met pittige! tomatensaus", "price": "€ 18,50"},

      {"category": "Visgerechten", "id": "A", "name": "Gamberoni al vino bianco", "description": "grote garnalen met knoflook, peterselie in witte wijn roomsaus. Met aardappelschijfjes, gemengde salade en broodjes.", "price": "€ 21,50"},
      {"category": "Visgerechten", "id": "B", "name": "Gamberoni alla pescatora", "description": "grote garnalen in tomatensaus met knoflook, peterselie, spaanse pepers. Met aardappelschijfjes, gemengde salade en broodjes.", "price": "€ 21,50"},
      {"category": "Visgerechten", "id": "C", "name": "Gamberoni alla gorgonzola", "description": "grote garnalen met witte wijn roomsaus, knoflook, peterselie in gorgonzola roomsaus. Met aardappelschijfjes, gemengde salade en broodjes.", "price": "€ 22,50"},
      {"category": "Visgerechten", "id": "D", "name": "Gamberoni arrosto", "description": "grote geroosterde garnalen met knoflook, peterselie, citroen. Met aardappelschijfjes, gemengde salade en broodjes.", "price": "€ 21,00"}
    ]
  },
  {
    id: "ni-hao-beilen",
    name: "Ni Hao",
    location: "Beilen",
    menu: [
      {category: "Bijgerechten", id: 1, name: "Kroepoek", price: "3.00"},
      {category: "Bijgerechten", id: 2, name: "Cassave Kroepoek", price: "3.00"},
      {category: "Bijgerechten", id: 3, name: "Loempia", price: "4.90"},
      {category: "Bijgerechten", id: 4, name: "Kip Loempia", price: "5.20"},
      {category: "Bijgerechten", id: 5, name: "Loempia met Babi Pangang", price: "7.20"},
      {category: "Bijgerechten", id: 6, name: "Loempia met Rundvlees", price: "7.50"},
      {category: "Bijgerechten", id: 7, name: "Loempia met 2 stokjes Saté", price: "7.20"}
    ]
  },
  {
    id: "kleine-moghul",
    name: "De Kleine Moghul",
    location: "Groningen",
    menu: [
    ]
  },
  {
    id: "sanaa-groningen",
    name: "Pizzeria Sanaa",
    location: "Groningen",
    menu: [
      {"id": "32", "name": "Pizza Dönner", "category": "Populaire keuze", "price": "11.50", "description": "Voor de dönnerliefhebbers, Dönnervlees, verse paprika en rode uien"},
      {"id": "", "name": "Carbonara Speciale", "category": "Populaire keuze", "price": "13.99", "description": "Ham, salami, spek, ossenhaas, rosbief, pittige worst en uien"},
      {"id": "23", "name": "Mechoui (Family plate mixed grill 2/3 pers.)", "category": "Populaire keuze", "price": "37.50", "description": "Speciaal bereid köfte vlees, lamskoteletten, kebab en kipfilet en daarbij een mix van shoarmavlees gebakken verse groenten keuze uit 3 soorten sausen"},
      {"id": "", "name": "Margherita", "category": "Vlees pizza", "price": "7.50", "description": "De meest basic pizza van alle pizza  Basis tomatensaus, kaas en mozzarellla"},
      {"id": "1", "name": "Salami", "category": "Vlees pizza", "price": "8.99", "description": "Een traditionele pizza met heerlijke tomatensaus en kaas"},
      {"id": "1", "name": "Prosciuto", "category": "Vlees pizza", "price": "8.50", "description": "Een traditionele pizza met heerlijke tomatensaus en kaas"},
      {"id": "2", "name": "Peperonata alla Mozzarella", "category": "Vlees pizza", "price": "9.50", "description": "Voor de liefhebbers een smaak heerlijke authentieke peperoni"},
      {"id": "3", "name": "Carbonara", "category": "Vlees pizza", "price": "11.50", "description": "Wereldberoemde vleespizza, Ham, salami, spek en verse knoflook"},
      {"id": "4", "name": "Suedese", "category": "Vlees pizza", "price": "10.50", "description": "Een Zweedse pizza Ham, ei en ui"},
      {"id": "5", "name": "Vulcano", "category": "Vlees pizza", "price": "9.50", "description": "Een stevige vuurvaste combinatie, Champignons en ham"},
      {"id": "6", "name": "Vesuvio", "category": "Vlees pizza", "price": "9.99", "description": "Heerlijke authentieke pizza, Champignons en salami"},
      {"id": "7", "name": "Montanara", "category": "Vlees pizza", "price": "11.50", "description": "Een combinatie van de vulcano & vesuvio Champignons, salami en ham"},
      {"id": "8", "name": "Capisco  ", "category": "Vlees pizza", "price": "10.00", "description": "Mozzarella, spek, ei en Parmezaanse kaas"},
      {"id": "9", "name": "Campagnola", "category": "Vlees pizza", "price": "11.50", "description": "Champignons, ham, paprika, uien en verse tomaten"},
      {"id": "10", "name": "Campagnola Speciale ", "category": "Vlees pizza", "price": "12.50", "description": "Champignons, ham, uien, paprika, asperges en gorgonzola"},
      {"id": "11", "name": "Quattro Stagoni", "category": "Vlees pizza", "price": "12.20", "description": "Champignons, ham, salami, artisjokken, olijven en kappertjes"},
      {"id": "12", "name": "Quattro Stagoni Speciale", "category": "Vlees pizza", "price": "13.30", "description": "Champignons, ham, salami, spek, artisjokken, mozzarella en ansjovis"},
      {"id": "13", "name": "Mista", "category": "Vlees pizza", "price": "12.99", "description": "Champignons, garnalen, ham, zalm en salami"},
      {"id": "14", "name": "Capricciosa", "category": "Vlees pizza", "price": "13.50", "description": "Ham, salami, zalm, garnalen, ui, kappertjes en verse paprika"},
      {"id": "15", "name": "Paesana", "category": "Vlees pizza", "price": "12.50", "description": "Pizza uit het Italiaanse binnenland, Champignons, spek, ham en salami"},
      {"id": "16", "name": "Paesana alla Gorgonzola", "category": "Vlees pizza", "price": "13.95", "description": "Champignons, ham, salami, spek, paprika, gorgonzola en pittige worst"},
      {"id": "17", "name": "Mafiosa", "category": "Vlees pizza", "price": "12.99", "description": "Gekruid gehakt vlees, ham, spek, champignons en broccoli"},
      {"id": "18", "name": "Del Re", "category": "Vlees pizza", "price": "14.50", "description": "Ossenhaas, ham, salami, champignons, spek, gorgonzola en paprika"},
      {"id": "19", "name": "Del Amore ", "category": "Vlees pizza", "price": "14.50", "description": "Champignons, rosbief, ham, salami, spek, ossenhaas en ananas"},
      {"id": "21", "name": "Di Pollo ", "category": "Vlees pizza", "price": "12.99", "description": "Gegrilde stukjes kipfilet, champignons, paprika en uien"},
      {"id": "22", "name": "Kip Dönner", "category": "Vlees pizza", "price": "11.50", "description": "kip dönner, paprika en pikanti"},
      {"id": "23", "name": "Pizza Hawaï", "category": "Vlees pizza", "price": "9.99", "description": "Ham, ananas & mozzarella Volgens de pizzatest de lekkerste Hawaï uit Groningen"},
      {"id": "24", "name": "Barbaresça", "category": "Vlees pizza", "price": "10.50", "description": "Nomadenpizza      Gekruid gehakt vlees, verse uien, ei, Parmezaanse kaas"},
      {"id": "25", "name": "Del Cacciatore", "category": "Vlees pizza", "price": "12.50", "description": "Ossenhaas, salami, paprika, mozzarella en gorgonzola"},
      {"id": "26", "name": "Del Bandito", "category": "Vlees pizza", "price": "12.99", "description": "Gegrilde kipfilet, salami, ossenhaas en verse groenten"},
      {"id": "27", "name": "Carossa Pikanti", "category": "Vlees pizza", "price": "13.50", "description": "De formule 1 onder de pizza’s, Rosbief, shoarmavlees, ui en spek"},
      {"id": "28", "name": "Napolitana", "category": "Vlees pizza", "price": "12.50", "description": "Verse basilicum, olijven, kappertjes, verse tomaten, ansjovis, mozzarella en peterselie"},
      {"id": "29", "name": "Inglese", "category": "Vlees pizza", "price": "13.50", "description": "Ossenhaas, verse tomaten, gorgonzola, broccoli, olijven, kappertjes en peterselie"},
      {"id": "30", "name": "Galbani alla Mozzarella", "category": "Vlees pizza", "price": "11.50", "description": "Ham, salami, mozzarella, uien, paprika en knoflook"},
      {"id": "31", "name": "Pizza Shoarma", "category": "Vlees pizza", "price": "10.99", "description": "De combinatie voor de shoarmaliefhebber, Shoarmavlees en ui  (knoflooksaus apart geserveerd)"},
      {"id": "32", "name": "Pizza Dönner", "category": "Vlees pizza", "price": "11.50", "description": "Voor de dönnerliefhebbers, Dönnervlees, verse paprika en rode uien  knoflooksaus (apart)"},
      {"id": "33", "name": "Mira ", "category": "Vlees pizza", "price": "13.00", "description": "Ham, salami, spek, ui, pittige worst en ei"},
      {"id": "34", "name": "Carbonara alla Gorgonzola", "category": "Vlees pizza", "price": "13.50", "description": "Ham, salami, spek, rosbief en gorgonzola"},
      {"id": "35", "name": "Carbonara Speciale ", "category": "Vlees pizza", "price": "13.99", "description": "Ham, salami, spek, ossenhaas, rosbief, pittige worst en uien"},
      {"id": "36", "name": "Carbonara di Mamma", "category": "Vlees pizza", "price": "13.50", "description": "Moeders recept,  Ham, salami, spek, uien, ei en gorgonzola"},
      {"id": "37", "name": "Tutti Frutti", "category": "Vlees pizza", "price": "12.50", "description": "Prachtige kleuren in een pizzacombinatie, Gemengd vers fruit, ham en mozzarella"},
      {"id": "38", "name": "Delicatezza Marina", "category": "Vis pizza’s", "price": "17.50", "description": "Grote gamba’s, gemarineerde zeeschelpen, paling, zalmsnippers en krab"},
      {"id": "39", "name": "Al Tonno", "category": "Vis pizza’s", "price": "8.99", "description": "Simpel in zijn eenvoud, Tonijn en uien"},
      {"id": "40", "name": "Veneziana", "category": "Vis pizza’s", "price": "12.50", "description": "Tonijn, garnalen, ansjovis, uien, olijven en verse knoflook"},
      {"id": "41", "name": "Gambri ", "category": "Vis pizza’s", "price": "13.50", "description": "Grote garnalen, krab, gerookte zalmsnippers en uien"},
      {"id": "42", "name": "Fungi Marinara ", "category": "Vis pizza’s", "price": "12.99", "description": "Gebakken champignons, tonijn, garnalen, krab en olijven"},
      {"id": "43", "name": "Frutti del Mare", "category": "Vis pizza’s", "price": "14.50", "description": "Fruit van de zee in een evenwichtige combinatie"},
      {"id": "44", "name": "Mediterrania", "category": "Vis pizza’s", "price": "15.50", "description": "Krab, grote garnalen, paling, mosselen, tonijn, zalm, inktvis, ansjovis, rode ui en pesto"},
      {"id": "45", "name": "La Mamma", "category": "Vegetarische pizza's", "price": "12.50", "description": "Verse tomaten, asperges, paprika, rode ui, mozzarella en gorgonzola"},
      {"id": "46", "name": "Fungi alla Mozzarella", "category": "Vegetarische pizza's", "price": "7.99", "description": "gekruide champignons en mozzarella"},
      {"id": "47", "name": "Pepperoni ", "category": "Vegetarische pizza's", "price": "9.50", "description": "Champignons, paprika, uien, olijven en Spaanse pepers"},
      {"id": "48", "name": "Vegetariana ", "category": "Vegetarische pizza's", "price": "10.00", "description": "Verse tomaten, champignons, artisjokken, broccoli en uien"},
      {"id": "49", "name": "Vegetariana speciale ", "category": "Vegetarische pizza's", "price": "12.50", "description": "Champignons, asperges, artisjokken, broccoli, mozzarella, maïs, spinazie, paprika, uien, pesto en olijven"},
      {"id": "50", "name": "Quattro Formaggi", "category": "Vegetarische pizza's", "price": "11.50", "description": "Vierluik van kaasspecialiteiten"},
      {"id": "51", "name": "Picasso", "category": "Specialiteiten", "price": "11.99", "description": "Verse tomaten, Broccoli, spinazie, asperges, maïs, ananas en gorgonzola"},
      {"id": "52", "name": "Quattro Formaggi Salami of Ham", "category": "Specialiteiten", "price": "12.50", "description": "Een kwartet van verschillende kazen met salami of ham"},
      {"id": "53", "name": "Sole Mio ", "category": "Specialiteiten", "price": "12.99", "description": "Pittige pepperoni, gorgonzola, mozzarella, Pomodori tomaten en rucola"},
      {"id": "54", "name": "Primavera", "category": "Specialiteiten", "price": "11.95", "description": "Vlees en vis in een gebalanceerde combinatie Ham, spek, garnalen, maïs en verse knoflook"},
      {"id": "55", "name": "Casa Nostra", "category": "Specialiteiten", "price": "16.50", "description": "De smaakknaller van onze eigen hand, Fantasie van de kok"},
      {"id": "56", "name": "Pepperonata al Verdi", "category": "Specialiteiten", "price": "11.95", "description": "Pittige pepperoni (worst), mozzarella, paprika, ui en Pomodori tomaten"},
      {"id": "57", "name": "Americana ", "category": "Specialiteiten", "price": "14.50", "description": "Gegrilde stukjes kipfilet, ossenhaas, rosbief, spek, broccoli, maïs en paprika"},
      {"id": "58", "name": "Olandese", "category": "Specialiteiten", "price": "12.50", "description": "Pizza met smaken van eigen Hollandse bodem Ham, spek, asperges, ei, rode ui en verse knoflook"},
      {"id": "61", "name": "Buon Gusto", "category": "Specialiteiten", "price": "11.50", "description": "Eenvoudige, maar rijke smaken, Kip, mozzarella en verse tomaten"},
      {"id": "62", "name": "Pizza alla Rucola", "category": "Specialiteiten", "price": "12.99", "description": "Ossenhaas, rosbief, rucola, pomodori tomaten en Parmezaanse kaas"},
      {"id": "64", "name": "Colombo", "category": "Specialiteiten", "price": "9.95", "description": "Zachte ham en stevige salami vormen een mooie combinatie"},
      {"id": "65", "name": "Chipolla", "category": "Specialiteiten", "price": "7.50", "description": "Italiaanse eenvoud, Pizzasaus kaas en uien"},
      {"id": "70", "name": "Calzone Simplice", "category": "Calzone", "price": "9.95", "description": "Dubbelgeslagen pizza, simpel maar heerlijk gevuld Ham en salami"},
      {"id": "71", "name": "Calzone alla Sicilliana ", "category": "Calzone", "price": "12.50", "description": "Dubbelgeslagen Sicilliaanse pizza, Ham, salami, mozzarella, gorgonzola en spek"},
      {"id": "72", "name": "Calzone alla Gorgonzola", "category": "Calzone", "price": "12.99", "description": "Gorgonzola, ham, salami, spek, olijven en paprika"},
      {"id": "73", "name": "Calzone Speciale ", "category": "Calzone", "price": "13.50", "description": "Ham, salami, rosbief, spek, pittige worst, paprika en verse knoflook"},
      {"id": "74", "name": "Calzone Di Mare", "category": "Calzone", "price": "13.50", "description": "Tonijn, gerookte zalm, garnalen, uien en verse knoflook"},
      {"id": "75", "name": "Calzone Vegetariana", "category": "Calzone", "price": "13.50", "description": "Verse groenten, verse knoflook en pesto"},
      {"id": "", "name": "Kaas en sla", "category": "Lahmachoun", "price": "5.50", "description": ""},
      {"id": "", "name": "Turkse worst, feta, kaas en gemengde sla", "category": "Lahmachoun", "price": "6.50", "description": ""},
      {"id": "", "name": "Shoarma super , met verse groenten en kaas", "category": "Lahmachoun", "price": "8.99", "description": ""},
      {"id": "", "name": "Döner kebab, sla en Feta kaas", "category": "Lahmachoun", "price": "8.50", "description": ""},
      {"id": "", "name": "Kipfilet, kaas en sla", "category": "Lahmachoun", "price": "8.50", "description": ""},
      {"id": "", "name": "Shoarmavlees en kaas", "category": "Lahmachoun", "price": "8.50", "description": ""},
      {"id": "", "name": "Mixshoarma extra vlees met sla", "category": "Pita broodjes", "price": "7.99", "description": ""},
      {"id": "", "name": "Döner kebab", "category": "Pita broodjes", "price": "7.99", "description": ""},
      {"id": "", "name": "Kipshoarma met sla", "category": "Pita broodjes", "price": "7.50", "description": ""},
      {"id": "", "name": "Pita kaas", "category": "Pita broodjes", "price": "3.00", "description": ""},
      {"id": "", "name": "Sujuc met kaas en sla", "category": "Pita broodjes", "price": "3.95", "description": ""},
      {"id": "", "name": "Hawaï met ham, ananas en kaas", "category": "Pita broodjes", "price": "3.99", "description": ""},
      {"id": "", "name": "Köfte met kaas en sla", "category": "Pita broodjes", "price": "6.50", "description": ""},
      {"id": "", "name": "Tonijn met kaas en sla ", "category": "Pita broodjes", "price": "4.00", "description": ""},
      {"id": "99", "name": "Spareribs, zoete marinadesaus", "category": "Schotels", "price": "17.95", "description": "Kalfsspareribs met aardappelschijfjes of patat"},
      {"id": "99", "name": "Spareribs, pittige marinadesaus", "category": "Schotels", "price": "18.95", "description": "Kalfsspareribs met aardappelschijfjes of patat"},
      {"id": "100", "name": "Mix shoarmavlees", "category": "Schotels", "price": "10.50", "description": "Met pita brood en knoflook saus"},
      {"id": "101", "name": "Shoarma tajin met pita brood en knoflook saus", "category": "Schotels", "price": "12.45", "description": "Verse paprika, rode uien en champignons"},
      {"id": "102", "name": "Shoarmavlees super met knoflook saus", "category": "Schotels", "price": "13.30", "description": "Verse groenten, ananas en kaas"},
      {"id": "104", "name": "Kebab tajin met pita brood en knoflook saus", "category": "Schotels", "price": "13.95", "description": "Gegrilde stukjes vlees met verse groenten."},
      {"id": "105", "name": "Lamskoteletten", "category": "Schotels", "price": "17.45", "description": "Speciaal gekruide lamskoteletten van de gril"},
      {"id": "106", "name": "Döner kebab kalfsvlees", "category": "Schotels", "price": "10.50", "description": "Met pita brood en knoflook saus"},
      {"id": "107", "name": "Kip Saté", "category": "Schotels", "price": "11.50", "description": "Gekruide kipfilet met satésaus"},
      {"id": "108", "name": "Kapsalon Döner kebab", "category": "Schotels", "price": "9.95", "description": "Keus uit: knoflook saus, uien saus, sambal"},
      {"id": "109", "name": "Kipdöner tajin", "category": "Schotels", "price": "9.50", "description": "Kipshoarma met verse gemengde groenten"},
      {"id": "110", "name": "Kipfilet", "category": "Schotels", "price": "9.50", "description": "Gemarineerde kipfilet"},
      {"id": "111", "name": "Kipfilet met kaas", "category": "Schotels", "price": "11.50", "description": "Kipfilet met gesmolten kaas"},
      {"id": "112", "name": "Kipfilet super", "category": "Schotels", "price": "12.50", "description": "Kipfilet met verse groenten, kaas en ananas"},
      {"id": "113", "name": "Mixed Grill", "category": "Vlees gerechten", "price": "16.50", "description": "Lamskoteletten, kebab, kipfilet ,kofta."},
      {"id": "115", "name": "Mechoui (Family plate mixed grill 2/3 pers.)", "category": "Vlees gerechten", "price": "37.50", "description": "Speciaal bereid köfte vlees, lamskoteletten, kebab en kipfilet en daarbij een mix van shoarmavlees gebakken  verse groenten keuze uit 3 soorten sausen"},
      {"id": "130", "name": "Bolognese", "category": "Lasagnes", "price": "11.50", "description": "Rundergehakt in tomatensaus"},
      {"id": "131", "name": "Marinara", "category": "Lasagnes", "price": "12.95", "description": "Lasagne met verschillende soorten zeevruchten"},
      {"id": "133", "name": "Quatro Formaggio", "category": "Lasagnes", "price": "12.50", "description": "Lasagne in een romige basissaus afgemaakt met vier kaasspecialiteiten"},
      {"id": "134", "name": "Contadino ", "category": "Lasagnes", "price": "10.95", "description": "Romige basissaus, champingnons, olijven en pesto"},
      {"id": "135", "name": "Vegetariana", "category": "Lasagnes", "price": "13.95", "description": "Romige basissaus met gezonde verse groenten"},
      {"id": "136", "name": "Galbani ", "category": "Lasagnes", "price": "10.95", "description": "Sanaa’s basissaus met rundergehakt en gorgonzola"},
      {"id": "137", "name": "Tasco", "category": "Lasagnes", "price": "13.50", "description": "Rundergehakt, champignons, mozzarella en gorgonzola"},
      {"id": "140", "name": "Quattro Formaggi", "category": "Pasta’s", "price": "10.95", "description": "Vier soorten kaas"},
      {"id": "141", "name": "Carbonara", "category": "Pasta’s", "price": "11.95", "description": "Witte saus met reepjes ham, spek, ei en Parmezaanse kaas"},
      {"id": "142", "name": "Del Ravioli", "category": "Pasta’s", "price": "10.95", "description": "Witte saus met gorgonzola, champignons, pesto en knoflook"},
      {"id": "143", "name": "Alla Salmoni", "category": "Pasta’s", "price": "12.95", "description": "Met zalm, bladspinazie en pesto"},
      {"id": "144", "name": "Vegetariana", "category": "Pasta’s", "price": "11.95", "description": "Met diverse verse groenten"},
      {"id": "145", "name": "Bolognese", "category": "Pasta’s", "price": "10.50", "description": "Rundergehakt in tomatensaus en Parmezaanse kaas"},
      {"id": "146", "name": "Arrabiata ", "category": "Pasta’s", "price": "9.99", "description": "Pikante saus, verse tomaten, ui, Parmezaanse kaas en basilicum"},
      {"id": "147", "name": "Matricciana ", "category": "Pasta’s", "price": "10.50", "description": "Reepjes ham, spek, Napolitanasaus, Parmezaanse kaas en verse knoflook"},
      {"id": "148", "name": "Campagnola", "category": "Pasta’s", "price": "12.50", "description": "Stukjes ossenhaas, blokjes tomaat, ui, verse knoflook en basilicum"},
      {"id": "149", "name": "Al Forno", "category": "Pasta’s", "price": "13.00", "description": "Rundergehakt in tomatensaus, reepjes ham en ei (uit de oven)"},
      {"id": "150", "name": " Frutti del Mare ", "category": "Pasta’s", "price": "12.99", "description": "Zeevruchten en verse knoflook"},
      {"id": "151", "name": "Gamba´s", "category": "Pasta’s", "price": "14.50", "description": "Tomaten saus, champignons, peterselie en Parmezaanse kaas"},
      {"id": "152", "name": "Marco Pollo", "category": "Pasta’s", "price": "13.50", "description": "Broccoli, uien, kipfilet, pesto, roomsaus en verse knoflook"},
      {"id": "153", "name": "Della Casa", "category": "Pasta’s", "price": "13.50", "description": "Romige saus, ossenhaas, broccoli, ui, champignons en Parmezaanse kaas"},
      {"id": "", "name": "Salata Mozzarella", "category": "Salades", "price": "4.95", "description": "Gemengde salade, mozzarella, Pomodori tomaten en komkommer"},
      {"id": "", "name": "Salata Mista", "category": "Salades", "price": "3.99", "description": "Gemengde salade, tomaten en komkommer"},
      {"id": "", "name": "Turkse Salade", "category": "Salades", "price": "4.99", "description": "Komkommer, tomaten, sujuc, feta kaas, uien en pitloze olijven"},
      {"id": "", "name": "Salata Tunna", "category": "Salades", "price": "5.95", "description": "Tonijn, ei, Pomodori tomaten ,rode uien, gemengde sla en kalamata"},
      {"id": "", "name": "Salade Gamba", "category": "Salades", "price": "7.99", "description": "Gamba´s, paprika, komkommer, tomaten en maïs"},
      {"id": "", "name": "Griekse Salade", "category": "Salades", "price": "6.50", "description": "Feta kaas, gemengde sla, komkommer, Pomodori tomaten, rode uien, kalamata olijven en paprika"},
      {"id": "", "name": "Brood met kruidenboter", "category": "Voor- en bijgerechten", "price": "4.50", "description": ""},
      {"id": "", "name": "Aardappelschijfjes met mayonaise", "category": "Voor- en bijgerechten", "price": "6.50", "description": ""},
      {"id": "", "name": "Fettakaas met kalamata olijven en gekruidbrood", "category": "Voor- en bijgerechten", "price": "5.50", "description": ""},
      {"id": "", "name": "Gekruide olijven (pitloos)", "category": "Voor- en bijgerechten", "price": "3.99", "description": ""},
      {"id": "", "name": "Extra lamsshoarma", "category": "Voor de Extra vlees liefhebber's", "price": "2.50", "description": ""},
      {"id": "", "name": "Extra kotleten", "category": "Voor de Extra vlees liefhebber's", "price": "4.50", "description": ""},
      {"id": "", "name": "Extra Doner kebab", "category": "Voor de Extra vlees liefhebber's", "price": "2.50", "description": ""},
      {"id": "", "name": "Extra ham", "category": "Voor de Extra vlees liefhebber's", "price": "1.90", "description": ""},
      {"id": "", "name": "Extra Belegde vlees", "category": "Voor de Extra vlees liefhebber's", "price": "4.20", "description": ""},
      {"id": "", "name": "Extra kip doner", "category": "Voor de Extra vlees liefhebber's", "price": "2.00", "description": ""},
      {"id": "", "name": "Extra salami", "category": "Voor de Extra vlees liefhebber's", "price": "2.00", "description": ""},
      {"id": "", "name": "Extra  spek", "category": "Voor de Extra vlees liefhebber's", "price": "2.50", "description": ""},
      {"id": "", "name": "Extra rosbief", "category": "Voor de Extra vlees liefhebber's", "price": "2.90", "description": ""},
      {"id": "", "name": "Extra ossenhaas", "category": "Voor de Extra vlees liefhebber's", "price": "3.10", "description": ""},
      {"id": "", "name": "Extra Sujuc", "category": "Voor de Extra vlees liefhebber's", "price": "2.00", "description": ""},
      {"id": "", "name": "Extra gehakt", "category": "Voor de Extra vlees liefhebber's", "price": "2.50", "description": ""},
      {"id": "", "name": "Extra kebab", "category": "Voor de Extra vlees liefhebber's", "price": "3.50", "description": ""},
      {"id": "", "name": "Extra kip", "category": "Voor de Extra vlees liefhebber's", "price": "3.00", "description": ""},
      {"id": "", "name": "Extra gegrilde kipfilet", "category": "Voor de Extra vlees liefhebber's", "price": "3.50", "description": ""},
      {"id": "", "name": "Extra Sparibs", "category": "Voor de Extra vlees liefhebber's", "price": "7.50", "description": ""},
      {"id": "", "name": "Extra inktvis", "category": "Extra's voor de zeevruchten liefhebbers", "price": "1.50", "description": ""},
      {"id": "", "name": "Extra grote gamba's ( 3 stukken )", "category": "Extra's voor de zeevruchten liefhebbers", "price": "5.50", "description": ""},
      {"id": "", "name": "Extra tonijn", "category": "Extra's voor de zeevruchten liefhebbers", "price": "2.00", "description": ""},
      {"id": "", "name": "Extra anjovis", "category": "Extra's voor de zeevruchten liefhebbers", "price": "1.90", "description": ""},
      {"id": "", "name": "Extra zalm", "category": "Extra's voor de zeevruchten liefhebbers", "price": "2.50", "description": ""},
      {"id": "", "name": "Extra garnalen", "category": "Extra's voor de zeevruchten liefhebbers", "price": "2.00", "description": ""},
      {"id": "", "name": "Extra groot garnalen.", "category": "Extra's voor de zeevruchten liefhebbers", "price": "3.50", "description": ""},
      {"id": "", "name": "Extra Paling", "category": "Extra's voor de zeevruchten liefhebbers", "price": "3.00", "description": ""},
      {"id": "", "name": "Extra Krap", "category": "Extra's voor de zeevruchten liefhebbers", "price": "1.50", "description": ""},
      {"id": "", "name": "Extra zeeschelpen", "category": "Extra's voor de zeevruchten liefhebbers", "price": "1.50", "description": ""},
      {"id": "", "name": "Extra verse tomaten", "category": "Voor de Extra Groenten liefhebber's ", "price": "0.50", "description": ""},
      {"id": "", "name": "Extra komkommer", "category": "Voor de Extra Groenten liefhebber's ", "price": "0.50", "description": ""},
      {"id": "", "name": "Extra kappertjes", "category": "Voor de Extra Groenten liefhebber's ", "price": "1.50", "description": ""},
      {"id": "", "name": "Extra champion", "category": "Voor de Extra Groenten liefhebber's ", "price": "0.50", "description": ""},
      {"id": "", "name": "Extra Kalamata olijven", "category": "Voor de Extra Groenten liefhebber's ", "price": "1.00", "description": ""},
      {"id": "", "name": "Extra paprika", "category": "Voor de Extra Groenten liefhebber's ", "price": "1.00", "description": ""},
      {"id": "", "name": "Extra Zwarte olijven (pitloos)", "category": "Voor de Extra Groenten liefhebber's ", "price": "1.20", "description": ""},
      {"id": "", "name": "Extra  uien", "category": "Voor de Extra Groenten liefhebber's ", "price": "0.90", "description": ""},
      {"id": "", "name": "Extra belegde groente", "category": "Voor de Extra Groenten liefhebber's ", "price": "2.50", "description": ""},
      {"id": "", "name": "Extra brokkoli", "category": "Voor de Extra Groenten liefhebber's ", "price": "1.00", "description": ""},
      {"id": "", "name": "Extra asperges", "category": "Voor de Extra Groenten liefhebber's ", "price": "1.10", "description": ""},
      {"id": "", "name": "Extra artisjokken", "category": "Voor de Extra Groenten liefhebber's ", "price": "1.30", "description": ""},
      {"id": "", "name": "Extra mais", "category": "Voor de Extra Groenten liefhebber's ", "price": "0.90", "description": ""},
      {"id": "", "name": "Extra spinazie", "category": "Voor de Extra Groenten liefhebber's ", "price": "1.00", "description": ""},
      {"id": "", "name": "Extra sla", "category": "Voor de Extra Groenten liefhebber's ", "price": "0.50", "description": ""},
      {"id": "", "name": "Extra jalapeno", "category": "Voor de Extra Groenten liefhebber's ", "price": "0.70", "description": ""},
      {"id": "", "name": "Extra pizza kaas", "category": "Extra's voor de kaas liefhebbers", "price": "1.90", "description": ""},
      {"id": "", "name": "Extra mozzerella", "category": "Extra's voor de kaas liefhebbers", "price": "2.00", "description": ""},
      {"id": "", "name": "Extra parmezano", "category": "Extra's voor de kaas liefhebbers", "price": "2.50", "description": ""},
      {"id": "", "name": "Extra feta kaas", "category": "Extra's voor de kaas liefhebbers", "price": "2.20", "description": ""},
      {"id": "", "name": "Extra Gorgonzola", "category": "Extra's voor de kaas liefhebbers", "price": "2.50", "description": ""},
      {"id": "", "name": "Aardappelschijfjes   of friet", "category": "Extra's", "price": "3.00", "description": ""},
      {"id": "", "name": "extra spare ribs", "category": "Extra's", "price": "7.50", "description": ""},
      {"id": "", "name": "Extra patat kruiden", "category": "Extra's", "price": "0.50", "description": ""},
      {"id": "", "name": "Pita", "category": "Extra's", "price": "0.70", "description": ""},
      {"id": "", "name": "Belegd", "category": "Extra's", "price": "3.50", "description": ""},
      {"id": "", "name": "Extra ei", "category": "Extra's", "price": "0.90", "description": ""},
      {"id": "", "name": "Extra knoflook", "category": "Extra's", "price": "0.90", "description": ""},
      {"id": "", "name": "Extra pesto", "category": "Extra's", "price": "1.10", "description": ""},
      {"id": "", "name": "Extra verse peper (pittig)", "category": "Extra's", "price": "0.90", "description": ""},
      {"id": "", "name": "Kruiden boter", "category": "Extra's", "price": "2.50", "description": ""},
      {"id": "", "name": "Gekruid brood", "category": "Extra's", "price": "2.00", "description": ""},
      {"id": "", "name": "Kalamata Olijven", "category": "Extra's", "price": "1.50", "description": ""},
      {"id": "", "name": "Cola", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "Fanta", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "7up", "category": "Drinken", "price": "2.30", "description": ""},
      {"id": "", "name": "Cola light", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "Cola zero", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "AA Drinken", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "Maaza Mango", "category": "Drinken", "price": "2.70", "description": ""},
      {"id": "", "name": "Auqarius Orange", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "Jus d'orange", "category": "Drinken", "price": "2.30", "description": ""},
      {"id": "", "name": "Appelsap", "category": "Drinken", "price": "2.30", "description": ""},
      {"id": "", "name": "Spa Blauw", "category": "Drinken", "price": "1.70", "description": ""},
      {"id": "", "name": "Spa Rood", "category": "Drinken", "price": "1.95", "description": ""},
      {"id": "", "name": "Fernades Super Pineapple", "category": "Drinken", "price": "2.20", "description": ""},
      {"id": "", "name": "Fernades Green Punch", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "Fernades Cherry Bouquet", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "Fernades Red grape", "category": "Drinken", "price": "2.50", "description": ""},
      {"id": "", "name": "Cola 1,5 L", "category": "Drinken", "price": "3.70", "description": ""},
      {"id": "", "name": "Fanta 1,5 L", "category": "Drinken", "price": "3.70", "description": ""},
      {"id": "", "name": "7up 1,5 L", "category": "Drinken", "price": "3.50", "description": ""},
      {"id": "", "name": "Uiensaus", "category": "Sauzen", "price": "1.00", "description": ""},
      {"id": "", "name": "Knoflooksaus", "category": "Sauzen", "price": "1.00", "description": ""},
      {"id": "", "name": "Turkse sambal", "category": "Sauzen", "price": "0.70", "description": ""},
      {"id": "", "name": "Cocktail saus", "category": "Sauzen", "price": "0.90", "description": ""},
      {"id": "", "name": "Mayonaise", "category": "Sauzen", "price": "0.50", "description": ""},
      {"id": "", "name": "Ketchup of Curry", "category": "Sauzen", "price": "0.50", "description": ""},
      {"id": "", "name": "Harissa", "category": "Sauzen", "price": "0.70", "description": ""},
      {"id": "", "name": "Kruidenboter ( zelfgemaak)", "category": "Sauzen", "price": "2.50", "description": ""}
    ]
  }
];

export const restaurantsByLocation = groupBy(restaurants, (r) => r.location);

export const getRestaurant = (id: string) => {
  const match = restaurants.find((restaurant) => restaurant.id === id);
  if (!match) throw new Error("Not found");
  return match;
};
